CREATE DATABASE IF NOT EXISTS mysns
--DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

USE mysns;

CREATE TABLE IF NOT EXISTS user(
    id VARCHAR(128) PRIMARY KEY,
    jsonstr VARCHAR(2048)
);

CREATE TABLE IF NOT EXISTS feed(
    no INT UNSIGNED PRIMARY KEY,
    id VARCHAR(128),
	jsonstr VARCHAR(8192)
);